version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: defaultpassword

  main:
    image: zengty/shop-docker
    depends_on:
      - "mysql"
    volumes:
      - ./uploads:/uploads
      - ./config:/config
    links:
    - mysql
    ports:
      - "4000:4000"
volumes:
  mysqldata: